<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AOSnifferParserDir>..\AOSnifferNET\PhotonPacketParser</AOSnifferParserDir>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClickableTransparentOverlay" Version="11.1.0" />
    <PackageReference Include="SharpPcap" Version="6.3.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="System.Reactive" Version="6.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AlbionDataHandlersNET8\AlbionDataHandlersNET8.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="PhotonPackageParser">
      <HintPath>$(AOSnifferParserDir)\PhotonPackageParser.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Protocol16">
      <HintPath>$(AOSnifferParserDir)\Protocol16.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Protocol18">
      <HintPath>$(AOSnifferParserDir)\Protocol18.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

</Project>
